name:                holonc
version:             0.1.0.0
github:              "fujiy00/holonc"
license:             BSD3
author:              "Yuuki Fujihara"
maintainer:          "mail@fujiy.me"
copyright:           "2018 Yuuki Fujihara"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Holon Compiler
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fujiy00/compiler#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- extra
- bytestring
- text
- data-binary-ieee754
- ghc
- ghc-paths
- filepath
- directory
- yaml
- data-default
- microlens
- microlens-mtl
- proto-lens
- proto-lens-protoc

library:
  source-dirs: src

executables:
  holonc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - holonc

tests:
  holonc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - holonc
